const actionsTypeUser = {
  LOGIN_REQUEST : 'LOGIN_REQUEST',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  LOAD_USER_DATA: 'LOAD_USER_DATA',
  SET_USER_DATA: 'SET_USER_DATA',
}

export default actionsTypeUser;